package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idClientes;
     private String nombre;
     private String apellido;
     private String direccion;
     private String observacion;
     private Integer margen;
     private Integer matricula;
     private String tipoIva;
     private Set ventases = new HashSet(0);
     private Set presupuestoses = new HashSet(0);
     private Set contactos = new HashSet(0);

    public Clientes() {
    }

    public Clientes(String nombre, String apellido, String direccion, String observacion, Integer margen, Integer matricula, String tipoIva, Set ventases, Set presupuestoses, Set contactos) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.observacion = observacion;
       this.margen = margen;
       this.matricula = matricula;
       this.tipoIva = tipoIva;
       this.ventases = ventases;
       this.presupuestoses = presupuestoses;
       this.contactos = contactos;
    }

    public Clientes(String nombre, String apellido, String direccion, String observacion, Integer margen, Integer matricula, String tipoIva) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.observacion = observacion;
        this.margen = margen;
        this.matricula = matricula;
        this.tipoIva = tipoIva;
    }

    
   
    public Integer getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(Integer idClientes) {
        this.idClientes = idClientes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getMargen() {
        return this.margen;
    }
    
    public void setMargen(Integer margen) {
        this.margen = margen;
    }
    public Integer getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Integer matricula) {
        this.matricula = matricula;
    }
    public String getTipoIva() {
        return this.tipoIva;
    }
    
    public void setTipoIva(String tipoIva) {
        this.tipoIva = tipoIva;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }
    public Set getPresupuestoses() {
        return this.presupuestoses;
    }
    
    public void setPresupuestoses(Set presupuestoses) {
        this.presupuestoses = presupuestoses;
    }
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }




}


