package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cuentacorriente generated by hbm2java
 */
public class Cuentacorriente  implements java.io.Serializable {


     private CuentacorrienteId id;
     private Ventas ventas;
     private Date fecha;
     private Double total;
     private Integer estado;
     private String formaDePago;

    public Cuentacorriente() {
    }

	
    public Cuentacorriente(Ventas ventas) {
        this.ventas = ventas;
    }
    public Cuentacorriente(Ventas ventas, Date fecha, Double total, Integer estado, String formaDePago) {
       this.ventas = ventas;
       this.fecha = fecha;
       this.total = total;
       this.estado = estado;
       this.formaDePago = formaDePago;
    }
   
    public CuentacorrienteId getId() {
        return this.id;
    }
    
    public void setId(CuentacorrienteId id) {
        this.id = id;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getFormaDePago() {
        return this.formaDePago;
    }
    
    public void setFormaDePago(String formaDePago) {
        this.formaDePago = formaDePago;
    }




}


