package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * DetallepresupuestosId generated by hbm2java
 */
public class DetallepresupuestosId  implements java.io.Serializable {


     private int idProductos;
     private int idPresupuestos;
     private int idClientes;

    public DetallepresupuestosId() {
    }

    public DetallepresupuestosId(int idProductos, int idPresupuestos, int idClientes) {
       this.idProductos = idProductos;
       this.idPresupuestos = idPresupuestos;
       this.idClientes = idClientes;
    }
   
    public int getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(int idProductos) {
        this.idProductos = idProductos;
    }
    public int getIdPresupuestos() {
        return this.idPresupuestos;
    }
    
    public void setIdPresupuestos(int idPresupuestos) {
        this.idPresupuestos = idPresupuestos;
    }
    public int getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(int idClientes) {
        this.idClientes = idClientes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallepresupuestosId) ) return false;
		 DetallepresupuestosId castOther = ( DetallepresupuestosId ) other; 
         
		 return (this.getIdProductos()==castOther.getIdProductos())
 && (this.getIdPresupuestos()==castOther.getIdPresupuestos())
 && (this.getIdClientes()==castOther.getIdClientes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProductos();
         result = 37 * result + this.getIdPresupuestos();
         result = 37 * result + this.getIdClientes();
         return result;
   }   


}


