package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * Detallepresupuestos generated by hbm2java
 */
public class Detallepresupuestos  implements java.io.Serializable {


     private DetallepresupuestosId id;
     private Presupuestos presupuestos;
     private Productos productos;
     private Integer cantidad;

    public Detallepresupuestos() {
    }

	
    public Detallepresupuestos(DetallepresupuestosId id, Presupuestos presupuestos, Productos productos) {
        this.id = id;
        this.presupuestos = presupuestos;
        this.productos = productos;
    }
    public Detallepresupuestos(DetallepresupuestosId id, Presupuestos presupuestos, Productos productos, Integer cantidad) {
       this.id = id;
       this.presupuestos = presupuestos;
       this.productos = productos;
       this.cantidad = cantidad;
    }
   
    public DetallepresupuestosId getId() {
        return this.id;
    }
    
    public void setId(DetallepresupuestosId id) {
        this.id = id;
    }
    public Presupuestos getPresupuestos() {
        return this.presupuestos;
    }
    
    public void setPresupuestos(Presupuestos presupuestos) {
        this.presupuestos = presupuestos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


