package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * DetalleventasId generated by hbm2java
 */
public class DetalleventasId  implements java.io.Serializable {


     private int idVentas;
     private int idClientes;
     private int idProductos;

    public DetalleventasId() {
    }

    public DetalleventasId(int idVentas, int idClientes, int idProductos) {
       this.idVentas = idVentas;
       this.idClientes = idClientes;
       this.idProductos = idProductos;
    }
   
    public int getIdVentas() {
        return this.idVentas;
    }
    
    public void setIdVentas(int idVentas) {
        this.idVentas = idVentas;
    }
    public int getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(int idClientes) {
        this.idClientes = idClientes;
    }
    public int getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(int idProductos) {
        this.idProductos = idProductos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleventasId) ) return false;
		 DetalleventasId castOther = ( DetalleventasId ) other; 
         
		 return (this.getIdVentas()==castOther.getIdVentas())
 && (this.getIdClientes()==castOther.getIdClientes())
 && (this.getIdProductos()==castOther.getIdProductos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVentas();
         result = 37 * result + this.getIdClientes();
         result = 37 * result + this.getIdProductos();
         return result;
   }   


}


