package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * Detalleventas generated by hbm2java
 */
public class Detalleventas  implements java.io.Serializable {


     private DetalleventasId id;
     private Productos productos;
     private Ventas ventas;
     private Integer cantidad;
     private Float iva;

    public Detalleventas() {
    }

	
    public Detalleventas(DetalleventasId id, Productos productos, Ventas ventas) {
        this.id = id;
        this.productos = productos;
        this.ventas = ventas;
    }
    public Detalleventas(DetalleventasId id, Productos productos, Ventas ventas, Integer cantidad, Float iva) {
       this.id = id;
       this.productos = productos;
       this.ventas = ventas;
       this.cantidad = cantidad;
       this.iva = iva;
    }
   
    public DetalleventasId getId() {
        return this.id;
    }
    
    public void setId(DetalleventasId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }




}


