package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Facturacion generated by hbm2java
 */
public class Facturacion  implements java.io.Serializable {


     private FacturacionId id;
     private Notadecredito notadecredito;
     private Notadedebito notadedebito;
     private Ventas ventas;
     private int cae;
     private int factura;
     private int puntoDeVenta;
     private Date fechaDeVencimiento;

    public Facturacion() {
    }

    public Facturacion(FacturacionId id, Notadecredito notadecredito, Notadedebito notadedebito, Ventas ventas, int cae, int factura, int puntoDeVenta, Date fechaDeVencimiento) {
       this.id = id;
       this.notadecredito = notadecredito;
       this.notadedebito = notadedebito;
       this.ventas = ventas;
       this.cae = cae;
       this.factura = factura;
       this.puntoDeVenta = puntoDeVenta;
       this.fechaDeVencimiento = fechaDeVencimiento;
    }
   
    public FacturacionId getId() {
        return this.id;
    }
    
    public void setId(FacturacionId id) {
        this.id = id;
    }
    public Notadecredito getNotadecredito() {
        return this.notadecredito;
    }
    
    public void setNotadecredito(Notadecredito notadecredito) {
        this.notadecredito = notadecredito;
    }
    public Notadedebito getNotadedebito() {
        return this.notadedebito;
    }
    
    public void setNotadedebito(Notadedebito notadedebito) {
        this.notadedebito = notadedebito;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public int getCae() {
        return this.cae;
    }
    
    public void setCae(int cae) {
        this.cae = cae;
    }
    public int getFactura() {
        return this.factura;
    }
    
    public void setFactura(int factura) {
        this.factura = factura;
    }
    public int getPuntoDeVenta() {
        return this.puntoDeVenta;
    }
    
    public void setPuntoDeVenta(int puntoDeVenta) {
        this.puntoDeVenta = puntoDeVenta;
    }
    public Date getFechaDeVencimiento() {
        return this.fechaDeVencimiento;
    }
    
    public void setFechaDeVencimiento(Date fechaDeVencimiento) {
        this.fechaDeVencimiento = fechaDeVencimiento;
    }




}


