package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * FacturacionId generated by hbm2java
 */
public class FacturacionId  implements java.io.Serializable {


     private int idFacturacion;
     private int idNotaDeCredito;
     private int idVentas;
     private int idClientes;
     private int idNotaDeDebito;

    public FacturacionId() {
    }

    public FacturacionId(int idFacturacion, int idNotaDeCredito, int idVentas, int idClientes, int idNotaDeDebito) {
       this.idFacturacion = idFacturacion;
       this.idNotaDeCredito = idNotaDeCredito;
       this.idVentas = idVentas;
       this.idClientes = idClientes;
       this.idNotaDeDebito = idNotaDeDebito;
    }
   
    public int getIdFacturacion() {
        return this.idFacturacion;
    }
    
    public void setIdFacturacion(int idFacturacion) {
        this.idFacturacion = idFacturacion;
    }
    public int getIdNotaDeCredito() {
        return this.idNotaDeCredito;
    }
    
    public void setIdNotaDeCredito(int idNotaDeCredito) {
        this.idNotaDeCredito = idNotaDeCredito;
    }
    public int getIdVentas() {
        return this.idVentas;
    }
    
    public void setIdVentas(int idVentas) {
        this.idVentas = idVentas;
    }
    public int getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(int idClientes) {
        this.idClientes = idClientes;
    }
    public int getIdNotaDeDebito() {
        return this.idNotaDeDebito;
    }
    
    public void setIdNotaDeDebito(int idNotaDeDebito) {
        this.idNotaDeDebito = idNotaDeDebito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturacionId) ) return false;
		 FacturacionId castOther = ( FacturacionId ) other; 
         
		 return (this.getIdFacturacion()==castOther.getIdFacturacion())
 && (this.getIdNotaDeCredito()==castOther.getIdNotaDeCredito())
 && (this.getIdVentas()==castOther.getIdVentas())
 && (this.getIdClientes()==castOther.getIdClientes())
 && (this.getIdNotaDeDebito()==castOther.getIdNotaDeDebito());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFacturacion();
         result = 37 * result + this.getIdNotaDeCredito();
         result = 37 * result + this.getIdVentas();
         result = 37 * result + this.getIdClientes();
         result = 37 * result + this.getIdNotaDeDebito();
         return result;
   }   


}


