package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formasdepago generated by hbm2java
 */
public class Formasdepago  implements java.io.Serializable {


     private Integer idFormasDePago;
     private String nombre;
     private Set ventasTienenFormasdepagos = new HashSet(0);
     private Set presupuestosTienenFormasdepagos = new HashSet(0);

    public Formasdepago() {
    }

    public Formasdepago(String nombre, Set ventasTienenFormasdepagos, Set presupuestosTienenFormasdepagos) {
       this.nombre = nombre;
       this.ventasTienenFormasdepagos = ventasTienenFormasdepagos;
       this.presupuestosTienenFormasdepagos = presupuestosTienenFormasdepagos;
    }
   
    public Integer getIdFormasDePago() {
        return this.idFormasDePago;
    }
    
    public void setIdFormasDePago(Integer idFormasDePago) {
        this.idFormasDePago = idFormasDePago;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVentasTienenFormasdepagos() {
        return this.ventasTienenFormasdepagos;
    }
    
    public void setVentasTienenFormasdepagos(Set ventasTienenFormasdepagos) {
        this.ventasTienenFormasdepagos = ventasTienenFormasdepagos;
    }
    public Set getPresupuestosTienenFormasdepagos() {
        return this.presupuestosTienenFormasdepagos;
    }
    
    public void setPresupuestosTienenFormasdepagos(Set presupuestosTienenFormasdepagos) {
        this.presupuestosTienenFormasdepagos = presupuestosTienenFormasdepagos;
    }




}


