package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lotes generated by hbm2java
 */
public class Lotes  implements java.io.Serializable {


     private int idLotes;
     private String nombre;
     private Date fechaVencimiento;
     private Set stocks = new HashSet(0);

    public Lotes() {
    }

	
    public Lotes(int idLotes) {
        this.idLotes = idLotes;
    }
    public Lotes(int idLotes, String nombre, Date fechaVencimiento, Set stocks) {
       this.idLotes = idLotes;
       this.nombre = nombre;
       this.fechaVencimiento = fechaVencimiento;
       this.stocks = stocks;
    }
   
    public int getIdLotes() {
        return this.idLotes;
    }
    
    public void setIdLotes(int idLotes) {
        this.idLotes = idLotes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


