package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Notadedebito generated by hbm2java
 */
public class Notadedebito  implements java.io.Serializable {


     private Integer idNotaDeDebito;
     private Set facturacions = new HashSet(0);

    public Notadedebito() {
    }

    public Notadedebito(Set facturacions) {
       this.facturacions = facturacions;
    }
   
    public Integer getIdNotaDeDebito() {
        return this.idNotaDeDebito;
    }
    
    public void setIdNotaDeDebito(Integer idNotaDeDebito) {
        this.idNotaDeDebito = idNotaDeDebito;
    }
    public Set getFacturacions() {
        return this.facturacions;
    }
    
    public void setFacturacions(Set facturacions) {
        this.facturacions = facturacions;
    }




}


