package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private PedidosId id;
     private Productos productos;
     private Proveedores proveedores;
     private Integer cantidad;
     private Date fecha;

    public Pedidos() {
    }

	
    public Pedidos(PedidosId id, Productos productos, Proveedores proveedores) {
        this.id = id;
        this.productos = productos;
        this.proveedores = proveedores;
    }
    public Pedidos(PedidosId id, Productos productos, Proveedores proveedores, Integer cantidad, Date fecha) {
       this.id = id;
       this.productos = productos;
       this.proveedores = proveedores;
       this.cantidad = cantidad;
       this.fecha = fecha;
    }
   
    public PedidosId getId() {
        return this.id;
    }
    
    public void setId(PedidosId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


