package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * PedidosId generated by hbm2java
 */
public class PedidosId  implements java.io.Serializable {


     private int idProveedores;
     private int idProductos;

    public PedidosId() {
    }

    public PedidosId(int idProveedores, int idProductos) {
       this.idProveedores = idProveedores;
       this.idProductos = idProductos;
    }
   
    public int getIdProveedores() {
        return this.idProveedores;
    }
    
    public void setIdProveedores(int idProveedores) {
        this.idProveedores = idProveedores;
    }
    public int getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(int idProductos) {
        this.idProductos = idProductos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidosId) ) return false;
		 PedidosId castOther = ( PedidosId ) other; 
         
		 return (this.getIdProveedores()==castOther.getIdProveedores())
 && (this.getIdProductos()==castOther.getIdProductos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProveedores();
         result = 37 * result + this.getIdProductos();
         return result;
   }   


}


