package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * PresupuestosTienenFormasdepago generated by hbm2java
 */
public class PresupuestosTienenFormasdepago  implements java.io.Serializable {


     private PresupuestosTienenFormasdepagoId id;
     private Formasdepago formasdepago;
     private Presupuestos presupuestos;
     private String obs;

    public PresupuestosTienenFormasdepago() {
    }

	
    public PresupuestosTienenFormasdepago(PresupuestosTienenFormasdepagoId id, Formasdepago formasdepago, Presupuestos presupuestos) {
        this.id = id;
        this.formasdepago = formasdepago;
        this.presupuestos = presupuestos;
    }
    public PresupuestosTienenFormasdepago(PresupuestosTienenFormasdepagoId id, Formasdepago formasdepago, Presupuestos presupuestos, String obs) {
       this.id = id;
       this.formasdepago = formasdepago;
       this.presupuestos = presupuestos;
       this.obs = obs;
    }
   
    public PresupuestosTienenFormasdepagoId getId() {
        return this.id;
    }
    
    public void setId(PresupuestosTienenFormasdepagoId id) {
        this.id = id;
    }
    public Formasdepago getFormasdepago() {
        return this.formasdepago;
    }
    
    public void setFormasdepago(Formasdepago formasdepago) {
        this.formasdepago = formasdepago;
    }
    public Presupuestos getPresupuestos() {
        return this.presupuestos;
    }
    
    public void setPresupuestos(Presupuestos presupuestos) {
        this.presupuestos = presupuestos;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }




}


