package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * PresupuestosId generated by hbm2java
 */
public class PresupuestosId  implements java.io.Serializable {


     private int idPresupuestos;
     private int idClientes;

    public PresupuestosId() {
    }

    public PresupuestosId(int idPresupuestos, int idClientes) {
       this.idPresupuestos = idPresupuestos;
       this.idClientes = idClientes;
    }
   
    public int getIdPresupuestos() {
        return this.idPresupuestos;
    }
    
    public void setIdPresupuestos(int idPresupuestos) {
        this.idPresupuestos = idPresupuestos;
    }
    public int getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(int idClientes) {
        this.idClientes = idClientes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PresupuestosId) ) return false;
		 PresupuestosId castOther = ( PresupuestosId ) other; 
         
		 return (this.getIdPresupuestos()==castOther.getIdPresupuestos())
 && (this.getIdClientes()==castOther.getIdClientes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPresupuestos();
         result = 37 * result + this.getIdClientes();
         return result;
   }   


}


