package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * PresupuestosTienenFormasdepagoId generated by hbm2java
 */
public class PresupuestosTienenFormasdepagoId  implements java.io.Serializable {


     private int idPresupuestos;
     private int idClientes;
     private int idFormasDePago;

    public PresupuestosTienenFormasdepagoId() {
    }

    public PresupuestosTienenFormasdepagoId(int idPresupuestos, int idClientes, int idFormasDePago) {
       this.idPresupuestos = idPresupuestos;
       this.idClientes = idClientes;
       this.idFormasDePago = idFormasDePago;
    }
   
    public int getIdPresupuestos() {
        return this.idPresupuestos;
    }
    
    public void setIdPresupuestos(int idPresupuestos) {
        this.idPresupuestos = idPresupuestos;
    }
    public int getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(int idClientes) {
        this.idClientes = idClientes;
    }
    public int getIdFormasDePago() {
        return this.idFormasDePago;
    }
    
    public void setIdFormasDePago(int idFormasDePago) {
        this.idFormasDePago = idFormasDePago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PresupuestosTienenFormasdepagoId) ) return false;
		 PresupuestosTienenFormasdepagoId castOther = ( PresupuestosTienenFormasdepagoId ) other; 
         
		 return (this.getIdPresupuestos()==castOther.getIdPresupuestos())
 && (this.getIdClientes()==castOther.getIdClientes())
 && (this.getIdFormasDePago()==castOther.getIdFormasDePago());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPresupuestos();
         result = 37 * result + this.getIdClientes();
         result = 37 * result + this.getIdFormasDePago();
         return result;
   }   


}


