package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProductos;
     private String nombre;
     private String descripcion;
     private Double precioVenta;
     private Double precioCompra;
     private Integer minimo;
     private Float motoIva;
     private Set detalleventases = new HashSet(0);
     private Set stocks = new HashSet(0);
     private Set detallepresupuestoses = new HashSet(0);
     private Set pedidoses = new HashSet(0);

    public Productos() {
    }

    public Productos(String nombre, String descripcion, Double precioVenta, Double precioCompra, Integer minimo, Float motoIva, Set detalleventases, Set stocks, Set detallepresupuestoses, Set pedidoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioVenta = precioVenta;
       this.precioCompra = precioCompra;
       this.minimo = minimo;
       this.motoIva = motoIva;
       this.detalleventases = detalleventases;
       this.stocks = stocks;
       this.detallepresupuestoses = detallepresupuestoses;
       this.pedidoses = pedidoses;
    }
   
    public Integer getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(Integer idProductos) {
        this.idProductos = idProductos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Double precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Double getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Double precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Integer getMinimo() {
        return this.minimo;
    }
    
    public void setMinimo(Integer minimo) {
        this.minimo = minimo;
    }
    public Float getMotoIva() {
        return this.motoIva;
    }
    
    public void setMotoIva(Float motoIva) {
        this.motoIva = motoIva;
    }
    public Set getDetalleventases() {
        return this.detalleventases;
    }
    
    public void setDetalleventases(Set detalleventases) {
        this.detalleventases = detalleventases;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getDetallepresupuestoses() {
        return this.detallepresupuestoses;
    }
    
    public void setDetallepresupuestoses(Set detallepresupuestoses) {
        this.detallepresupuestoses = detallepresupuestoses;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


