package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private int idProveedores;
     private String nombre;
     private String nombreRepresentante;
     private String apellidoRepresentante;
     private Set pedidoses = new HashSet(0);
     private Set contactos = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(int idProveedores) {
        this.idProveedores = idProveedores;
    }
    public Proveedores(int idProveedores, String nombre, String nombreRepresentante, String apellidoRepresentante, Set pedidoses, Set contactos) {
       this.idProveedores = idProveedores;
       this.nombre = nombre;
       this.nombreRepresentante = nombreRepresentante;
       this.apellidoRepresentante = apellidoRepresentante;
       this.pedidoses = pedidoses;
       this.contactos = contactos;
    }
   
    public int getIdProveedores() {
        return this.idProveedores;
    }
    
    public void setIdProveedores(int idProveedores) {
        this.idProveedores = idProveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreRepresentante() {
        return this.nombreRepresentante;
    }
    
    public void setNombreRepresentante(String nombreRepresentante) {
        this.nombreRepresentante = nombreRepresentante;
    }
    public String getApellidoRepresentante() {
        return this.apellidoRepresentante;
    }
    
    public void setApellidoRepresentante(String apellidoRepresentante) {
        this.apellidoRepresentante = apellidoRepresentante;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }




}


