package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * StockId generated by hbm2java
 */
public class StockId  implements java.io.Serializable {


     private int idStock;
     private int idProductos;
     private int idLotes;
     private int idDepositos;

    public StockId() {
    }

    public StockId(int idStock, int idProductos, int idLotes, int idDepositos) {
       this.idStock = idStock;
       this.idProductos = idProductos;
       this.idLotes = idLotes;
       this.idDepositos = idDepositos;
    }
   
    public int getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(int idStock) {
        this.idStock = idStock;
    }
    public int getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(int idProductos) {
        this.idProductos = idProductos;
    }
    public int getIdLotes() {
        return this.idLotes;
    }
    
    public void setIdLotes(int idLotes) {
        this.idLotes = idLotes;
    }
    public int getIdDepositos() {
        return this.idDepositos;
    }
    
    public void setIdDepositos(int idDepositos) {
        this.idDepositos = idDepositos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StockId) ) return false;
		 StockId castOther = ( StockId ) other; 
         
		 return (this.getIdStock()==castOther.getIdStock())
 && (this.getIdProductos()==castOther.getIdProductos())
 && (this.getIdLotes()==castOther.getIdLotes())
 && (this.getIdDepositos()==castOther.getIdDepositos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdStock();
         result = 37 * result + this.getIdProductos();
         result = 37 * result + this.getIdLotes();
         result = 37 * result + this.getIdDepositos();
         return result;
   }   


}


