package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private StockId id;
     private Deposito deposito;
     private Lotes lotes;
     private Productos productos;
     private int cantidad;
     private Date fecha;
     private Double precioCompra;
     private Double precioVenta;

    public Stock() {
    }

	
    public Stock(StockId id, Deposito deposito, Lotes lotes, Productos productos, int cantidad) {
        this.id = id;
        this.deposito = deposito;
        this.lotes = lotes;
        this.productos = productos;
        this.cantidad = cantidad;
    }
    public Stock(StockId id, Deposito deposito, Lotes lotes, Productos productos, int cantidad, Date fecha, Double precioCompra, Double precioVenta) {
       this.id = id;
       this.deposito = deposito;
       this.lotes = lotes;
       this.productos = productos;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
    }
   
    public StockId getId() {
        return this.id;
    }
    
    public void setId(StockId id) {
        this.id = id;
    }
    public Deposito getDeposito() {
        return this.deposito;
    }
    
    public void setDeposito(Deposito deposito) {
        this.deposito = deposito;
    }
    public Lotes getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Lotes lotes) {
        this.lotes = lotes;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Double precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Double precioVenta) {
        this.precioVenta = precioVenta;
    }




}


