package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private VentasId id;
     private Clientes clientes;
     private Double total;
     private Date fechaHora;
     private Integer interes;
     private Integer descuento;
     private Double ivatotal;
     private String tipoDeServicio;
     private Date fechaDesde;
     private Date fechaHasta;
     private Double rentas;
     private Set detalleventases = new HashSet(0);
     private Set ventasTienenFormasdepagos = new HashSet(0);
     private Cuentacorriente cuentacorriente;
     private Set facturacions = new HashSet(0);

    public Ventas() {
    }

	
    public Ventas(VentasId id, Clientes clientes) {
        this.id = id;
        this.clientes = clientes;
    }
    public Ventas(VentasId id, Clientes clientes, Double total, Date fechaHora, Integer interes, Integer descuento, Double ivatotal, String tipoDeServicio, Date fechaDesde, Date fechaHasta, Double rentas, Set detalleventases, Set ventasTienenFormasdepagos, Cuentacorriente cuentacorriente, Set facturacions) {
       this.id = id;
       this.clientes = clientes;
       this.total = total;
       this.fechaHora = fechaHora;
       this.interes = interes;
       this.descuento = descuento;
       this.ivatotal = ivatotal;
       this.tipoDeServicio = tipoDeServicio;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.rentas = rentas;
       this.detalleventases = detalleventases;
       this.ventasTienenFormasdepagos = ventasTienenFormasdepagos;
       this.cuentacorriente = cuentacorriente;
       this.facturacions = facturacions;
    }
   
    public VentasId getId() {
        return this.id;
    }
    
    public void setId(VentasId id) {
        this.id = id;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Integer getInteres() {
        return this.interes;
    }
    
    public void setInteres(Integer interes) {
        this.interes = interes;
    }
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }
    public Double getIvatotal() {
        return this.ivatotal;
    }
    
    public void setIvatotal(Double ivatotal) {
        this.ivatotal = ivatotal;
    }
    public String getTipoDeServicio() {
        return this.tipoDeServicio;
    }
    
    public void setTipoDeServicio(String tipoDeServicio) {
        this.tipoDeServicio = tipoDeServicio;
    }
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
    public Double getRentas() {
        return this.rentas;
    }
    
    public void setRentas(Double rentas) {
        this.rentas = rentas;
    }
    public Set getDetalleventases() {
        return this.detalleventases;
    }
    
    public void setDetalleventases(Set detalleventases) {
        this.detalleventases = detalleventases;
    }
    public Set getVentasTienenFormasdepagos() {
        return this.ventasTienenFormasdepagos;
    }
    
    public void setVentasTienenFormasdepagos(Set ventasTienenFormasdepagos) {
        this.ventasTienenFormasdepagos = ventasTienenFormasdepagos;
    }
    public Cuentacorriente getCuentacorriente() {
        return this.cuentacorriente;
    }
    
    public void setCuentacorriente(Cuentacorriente cuentacorriente) {
        this.cuentacorriente = cuentacorriente;
    }
    public Set getFacturacions() {
        return this.facturacions;
    }
    
    public void setFacturacions(Set facturacions) {
        this.facturacions = facturacions;
    }




}


