package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * VentasId generated by hbm2java
 */
public class VentasId  implements java.io.Serializable {


     private int idVentas;
     private int idClientes;

    public VentasId() {
    }

    public VentasId(int idVentas, int idClientes) {
       this.idVentas = idVentas;
       this.idClientes = idClientes;
    }
   
    public int getIdVentas() {
        return this.idVentas;
    }
    
    public void setIdVentas(int idVentas) {
        this.idVentas = idVentas;
    }
    public int getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(int idClientes) {
        this.idClientes = idClientes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentasId) ) return false;
		 VentasId castOther = ( VentasId ) other; 
         
		 return (this.getIdVentas()==castOther.getIdVentas())
 && (this.getIdClientes()==castOther.getIdClientes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVentas();
         result = 37 * result + this.getIdClientes();
         return result;
   }   


}


