package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * VentasTienenFormasdepagoId generated by hbm2java
 */
public class VentasTienenFormasdepagoId  implements java.io.Serializable {


     private int ventasIdVentas;
     private int ventasIdClientes;
     private int formasDePagoIdFormasDePago;

    public VentasTienenFormasdepagoId() {
    }

    public VentasTienenFormasdepagoId(int ventasIdVentas, int ventasIdClientes, int formasDePagoIdFormasDePago) {
       this.ventasIdVentas = ventasIdVentas;
       this.ventasIdClientes = ventasIdClientes;
       this.formasDePagoIdFormasDePago = formasDePagoIdFormasDePago;
    }
   
    public int getVentasIdVentas() {
        return this.ventasIdVentas;
    }
    
    public void setVentasIdVentas(int ventasIdVentas) {
        this.ventasIdVentas = ventasIdVentas;
    }
    public int getVentasIdClientes() {
        return this.ventasIdClientes;
    }
    
    public void setVentasIdClientes(int ventasIdClientes) {
        this.ventasIdClientes = ventasIdClientes;
    }
    public int getFormasDePagoIdFormasDePago() {
        return this.formasDePagoIdFormasDePago;
    }
    
    public void setFormasDePagoIdFormasDePago(int formasDePagoIdFormasDePago) {
        this.formasDePagoIdFormasDePago = formasDePagoIdFormasDePago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentasTienenFormasdepagoId) ) return false;
		 VentasTienenFormasdepagoId castOther = ( VentasTienenFormasdepagoId ) other; 
         
		 return (this.getVentasIdVentas()==castOther.getVentasIdVentas())
 && (this.getVentasIdClientes()==castOther.getVentasIdClientes())
 && (this.getFormasDePagoIdFormasDePago()==castOther.getFormasDePagoIdFormasDePago());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVentasIdVentas();
         result = 37 * result + this.getVentasIdClientes();
         result = 37 * result + this.getFormasDePagoIdFormasDePago();
         return result;
   }   


}


