package Modelo;
// Generated 23-ago-2016 20:56:16 by Hibernate Tools 4.3.1



/**
 * VentasTienenFormasdepago generated by hbm2java
 */
public class VentasTienenFormasdepago  implements java.io.Serializable {


     private VentasTienenFormasdepagoId id;
     private Formasdepago formasdepago;
     private Ventas ventas;
     private String obs;

    public VentasTienenFormasdepago() {
    }

	
    public VentasTienenFormasdepago(VentasTienenFormasdepagoId id, Formasdepago formasdepago, Ventas ventas) {
        this.id = id;
        this.formasdepago = formasdepago;
        this.ventas = ventas;
    }
    public VentasTienenFormasdepago(VentasTienenFormasdepagoId id, Formasdepago formasdepago, Ventas ventas, String obs) {
       this.id = id;
       this.formasdepago = formasdepago;
       this.ventas = ventas;
       this.obs = obs;
    }
   
    public VentasTienenFormasdepagoId getId() {
        return this.id;
    }
    
    public void setId(VentasTienenFormasdepagoId id) {
        this.id = id;
    }
    public Formasdepago getFormasdepago() {
        return this.formasdepago;
    }
    
    public void setFormasdepago(Formasdepago formasdepago) {
        this.formasdepago = formasdepago;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }




}


